# -*- coding: utf-8 -*-
"""peopletracking.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14KRPq0i4zEa3ORHXSuPXcJyS0iZrY8LJ
"""

from google.colab import drive
drive.mount('/content/gdrive')

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/ultralytics/yolov5  # clone repo
# %cd yolov5
# %pip install -qr requirements.txt  # install dependencies

import torch
from IPython.display import Image, clear_output  # to display images

clear_output()
print(f"Setup complete. Using torch {torch.__version__} ({torch.cuda.get_device_properties(0).name if torch.cuda.is_available() else 'CPU'})")

!unzip -q ../train_data.zip -d ../

!python train.py --img 640 --batch 10 --epochs 40 --data /content/yolov5/data/custom_data.yaml --weights yolov5x.pt --cache

!python detect.py --weights /content/yolov5/runs/train/exp/weights/best.pt --img 640 --conf 0.25 --source terrorist.mp4